### ISSUE TITLE
when switching branches, focus moves from integrated terminal

### ISSUE THREAD

**Issue by stw-ableton** [avaly/vscode-restore-git-branch-tabs#6]
when switching branches using the integrated vs code terminal, the focus moves away from the terminal, meaning you have to click on it in in order to run commands again.

it's very common that the first thing one does after switching branches is a pull, merge etc, so having to click into the terminal slows down workflow a little. retaining focus on the terminal is also default vs code behaviour when switching branches without this extension.

**Comment by romunov** [comment]
This is the same behavior I noticed and it would be neat if focus remained where it was before switching branches.
